"""add_user_status_fields

Revision ID: a7331a73dfbf
Revises: 6b455b5ccbc1
Create Date: 2026-06-16 12:16:29.022623

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a7331a73dfbf'
down_revision: Union[str, Sequence[str], None] = '6b455b5ccbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('users', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_at')
    op.drop_column('users', 'error_message')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
