services:
  nginx-gateway:
    image: nginx:alpine
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service
  auth-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
  auth-service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    depends_on:
      - auth-db
    env_file:
      - .env
  inventory-service:
    build:
      context: .
      dockerfile: inventory_service/Dockerfile
  kafka-broker:
    build:
      context: .
      dockerfile: kafka_broker/Dockerfile
  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
  order-service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
  product-service:
    build:
      context: .
      dockerfile: product_service/Dockerfile
  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    depends_on:
      - user-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://${USER_DB_USER}:${USER_DB_PASSWORD}@user-db:5432/${USER_DB_NAME}
  user-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${USER_DB_USER}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}