events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:8001;
    }

    server {
        listen 8000;

        location /api/v1/auth/health {
            proxy_pass http://auth_service/api/v1/auth/health;
            proxy_set_header Host $host;
        }

        location /api/v1/health/docs {
            proxy_pass http://auth_service/docs;
            proxy_set_header Host $host;
        }

        location /openapi.json {
            proxy_pass http://auth_service/openapi.json;
            proxy_set_header Host $host;
        }

    }
}