[project]
name = "pet"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]

[tool.uv.workspace]
members = [
    "api-gateway",
    "auth-service",
    "inventory-service",
    "kafka-broker",
    "notification-service",
    "order-service",
    "product-service",
    "user-service",
]
