[project]
name = "pet"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "isort>=8.0.1",
    "mypy>=1.20.2",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
]

[tool.uv.workspace]
members = [
    "api_gateway",
    "auth_service",
    "inventory_service",
    "kafka_broker",
    "notification_service",
    "order_service",
    "product_service",
    "user_service",
]
[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = [
    ".",
    "auth_service",
    "inventory_service",
    "notification_service",
    "order_service",
    "product_service",
    "user_service"
]
testpaths = [
    "auth_service/tests",
    "inventory_service/tests",
    "notification_service/tests",
    "order_service/tests",
    "product_service/tests",
    "user_service/tests"
]