name: Check
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: uv install
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install deps
        run: uv sync --all-packages

      - name: ruff
        run: uv run ruff check

      - name: isort
        run: uv run isort . --check-only --diff

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service: [auth_service]

    steps:
      - uses: actions/checkout@v6

      - name: uv install
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install deps
        run: uv sync --all-packages

      - name: Start all databases with Docker Compose
        run: docker compose -f docker-compose.test.yml up -d

      - name: Run tests for ${{ matrix.service }}
        run: uv run pytest ${{ matrix.service }} --cov=${{ matrix.service }}/src

      - name: Stop databases
        run: docker compose -f docker-compose.test.yml down
