name: Check
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: uv install
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install deps
        run: uv sync

      - name: ruff
        run: uv run ruff check

      - name: isort
        run: uv run isort . --check-only --diff

      - name: tests
        run: uv run pytest --cov=. --cov-fail-under=80
